# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: CANPeek
site_url: https://mydomain.org/mysite
repo_url: https://github.com/denis-jullien/CANPeek
theme:
  name: material
  logo: canpeek.png
  favicon: canpeek.png
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference

nav:
  - CANPeek: index.md
  - CAN Interface Setup:
    - interfaces/index.md
    - SocketCAN: interfaces/socketcan.md
    - PCAN: interfaces/pcan.md
    - Kvaser: interfaces/kvaser.md
    - Vector: interfaces/vector.md
    - Other Interfaces: interfaces/other.md
  - User Guide:
    - Getting Started: user_guide/getting_started.md
    - Main Window: user_guide/main_window.md
    - Projects: user_guide/projects.md
    - Filtering: user_guide/filtering.md
    - Transmitting Frames: user_guide/transmitting.md
    - CANopen: user_guide/canopen.md
    - Logging: user_guide/logging.md

