[project]
name = "canpeek"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cantools>=40.2.3",
    "pyqtdarktheme>=2.1.0",
    "pyside6>=6.9.1",
    "python-can>=4.5.0",
]
