name: Binary Build

on:
  push:
    tags:
      # Publish on any tag starting with a `v`, e.g. v1.2.3
      - v*
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    env:
      PYTHON_VERSION: "3.12"

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - run: uv add nuitka

      - name: Install ccache
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y patchelf
#          sudo apt-get update && sudo apt-get install -y ccache patchelf

#      - name: Setup Environment Variables
#        shell: bash
#        run: |
#          echo "NUITKA_CACHE_DIR=${{ github.action_path }}/nuitka/cache" >> $GITHUB_ENV
#
#      - name: Cache Nuitka cache directory
#        uses: actions/cache@v4
#        with:
#          path: ${{ env.NUITKA_CACHE_DIR }}
#          key: nuitka-${{ inputs.caching-key }}-${{ runner.os }}-${{ runner.arch }}-python-${{ env.PYTHON_VERSION }}-nuitka-${{ github.sha }}
#          restore-keys: |
#            nuitka-${{ inputs.caching-key }}-${{ runner.os }}-${{ runner.arch }}-python-${{ env.PYTHON_VERSION }}-
#            nuitka-${{ runner.os }}-${{ runner.arch }}-python-${{ env.PYTHON_VERSION }}-
#            nuitka-${{ runner.os }}-${{ runner.arch }}-

      - run: uv run -m nuitka src/canpeek/__main__.py --mode=app --enable-plugins=pyside6 --include-package=can.interfaces --include-package-data=qt_themes

#      - name: Build Executable
#        uses: Nuitka/Nuitka-Action@main
#        with:
#          nuitka-version: main
#          script-name: src/canpeek/__main__.py
#          mode: app
#          enable-plugins: pyside6
#          include-package: can.interfaces
#          include-package-data: qt_themes

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
          include-hidden-files: true